### ISSUE TITLE
Weird flavour combinations in vrap

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/hawaiian_vrap#23]
@cschwan has noticed some weird flavour combinations in the pineappl grids made with vrap, where for instance we don't have c-cbar contributions while we do have all the other flavours.

Looking through the code he found some weird things like this line here

https://github.com/NNPDF/hawaiian_vrap/blob/c370769bfdb56cfec369038998adffa1dad5a92f/src/Vlumifns_LHApdf.C#L49-L56

in which for instance we have (L49-50) `f_u * f_dbar * ckm + f_u*f_s*ckm`

is this correct? Why shouldn't it actually be `f_u*f_sbar`?

We believe this is not introducing any actual effect since we have agreement with Apfel (so if there is a bug, it is reproduce in both codes) but we were wondering whether you had some insight @enocera ?

**Comment by cschwan** [comment]
Line 50 also appears also again in line 61, and since both of them cover different hadronic initial states my deduction would be that one of the lines is wrong. I'd bet it's the proton-proton case given that `fWp == 1` suggest a W+ is being produced.

If this is a bug, it's already present in the original and unmodified Vrap on Lance Dixon's homepage: <https://www.slac.stanford.edu/%7Elance/Vrap/>

**Comment by cschwan** [comment]
That specific branch is never a problem for us because we always have `VectorBoson: Zgamma` which sets `fWp = 0` and `fWm = 0`.

**Comment by cschwan** [comment]
In the `pp` collider case, https://github.com/NNPDF/hawaiian_vrap/blob/c370769bfdb56cfec369038998adffa1dad5a92f/src/Vlumifns_LHApdf.C#L105-L109 it seems someone assumes the equality of the charm and anti-charm PDFs (in line 106, otherwise the factor 2 would be double counting). In line 109 the same for bottom- and anti-bottom PDFs.

Could this be historical? Vrap-0.9 was released on 28/7/2010.

**Comment by scarlehoff** [comment]
> Could this be historical? Vrap-0.9 was released on 28/7/2010.

From my point of view it is *prehistorical*

**Comment by cschwan** [comment]
PR #25 should fix this.
